FROM golang:1.21-alpine AS build

RUN apk add --no-cache make

WORKDIR /app

COPY . ./
RUN make blog-build

FROM alpine:latest

WORKDIR /app
COPY --from=build /app/blog-server.exe .
COPY --from=build /app/internal/blog/web/templates/ internal/blog/web/templates/
COPY --from=build /app/internal/blog/web/css/ internal/blog/web/css/
COPY --from=build /app/internal/blog/web/images/ internal/blog/web/images/

ENTRYPOINT ["/app/blog-server.exe"]