CREATE TABLE `photo_studios` (
    `id` VARCHAR(128) PRIMARY KEY NOT NULL,
    `name` VARCHAR(128) NOT NULL, -- TODO: Rethink MAX length
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
