version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/.service/blog2/"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/.service/photodx/bff/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/blog2/_ts/"
    schedule:
      interval: "daily"
