services:
  blog2-mysql:
    build:
      dockerfile: Dockerfile.mysql
      context: ./.service/blog2/
    platform: linux/arm64
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    volumes:
      - ./.service/blog2/.conf.d:/etc/mysql/conf.d
    ports:
      - 3307:3306
  photodx-mysql:
    build:
      dockerfile: Dockerfile
      context: ./.service/photodx/db/
    platform: linux/arm64
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    volumes:
      - ./.service/photodx/db/.conf.d:/etc/mysql/conf.d
    ports:
      - 3308:3306
