services:
  blog2-mysql:
    build:
      dockerfile: Dockerfile.mysql
      context: ./.service/blog2/
    platform: linux/arm64
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    volumes:
      - ./.service/blog2/.conf.d:/etc/mysql/conf.d
    ports:
      - 3307:3306
  crawler-firebase-emulator:
    build:
      dockerfile: Dockerfile.firebase
      context: ./.service/crawler/
    working_dir: /opt/app
    volumes:
      - ./.service/crawler:/opt/app
    command: /bin/sh -c '/usr/local/bin/firebase emulators:start --project=dummy-prj'
    ports:
      - 8081:8081
      - 8082:8082
      - 8083:8083