[build]
cmd = "make blog2-build-server"
bin = "./blog2-server.out"
include_dir = [
    "blog2"
]
exclude_dir = [
    "blog2/internal/web/_css",
    "blog2/internal/web/_images",
    "blog2/internal/web/_templates",
    "blog2/_ts"
]
stop_on_error = true