apiVersion: skaffold/v4beta7
kind: Config
metadata: 
  name: deploy-run-quickstart
profiles:
- name: stg
  manifests:
    rawYaml:
    - run-service-stg.yaml
# - name: prd
#   manifests:
#     rawYaml:
#     - run-service-prd.yaml
deploy:
  cloudrun: {}