// Code generated by MockGen. DO NOT EDIT.
// Source: crawler/crawler/internal/usecase/crawlerfactory/crawlerfactory2.go
//
// Generated by this command:
//
//	mockgen -source crawler/crawler/internal/usecase/crawlerfactory/crawlerfactory2.go -package crawlerfactory -destination crawler/crawler/internal/usecase/crawlerfactory/crawlerfactory2_mock.go
//
// Package crawlerfactory is a generated GoMock package.
package crawlerfactory

import (
	context "context"
	reflect "reflect"

	crawler "github.com/suzuito/sandbox2-go/crawler/crawler/internal/entity/crawler"
	gomock "go.uber.org/mock/gomock"
)

// MockCrawlerFactory2 is a mock of CrawlerFactory2 interface.
type MockCrawlerFactory2 struct {
	ctrl     *gomock.Controller
	recorder *MockCrawlerFactory2MockRecorder
}

// MockCrawlerFactory2MockRecorder is the mock recorder for MockCrawlerFactory2.
type MockCrawlerFactory2MockRecorder struct {
	mock *MockCrawlerFactory2
}

// NewMockCrawlerFactory2 creates a new mock instance.
func NewMockCrawlerFactory2(ctrl *gomock.Controller) *MockCrawlerFactory2 {
	mock := &MockCrawlerFactory2{ctrl: ctrl}
	mock.recorder = &MockCrawlerFactory2MockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCrawlerFactory2) EXPECT() *MockCrawlerFactory2MockRecorder {
	return m.recorder
}

// GetCrawler mocks base method.
func (m *MockCrawlerFactory2) GetCrawler(ctx context.Context, crawlerID crawler.CrawlerID) (*crawler.Crawler2, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCrawler", ctx, crawlerID)
	ret0, _ := ret[0].(*crawler.Crawler2)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCrawler indicates an expected call of GetCrawler.
func (mr *MockCrawlerFactory2MockRecorder) GetCrawler(ctx, crawlerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCrawler", reflect.TypeOf((*MockCrawlerFactory2)(nil).GetCrawler), ctx, crawlerID)
}

// GetCrawlers mocks base method.
func (m *MockCrawlerFactory2) GetCrawlers(ctx context.Context, crawlerIDs ...crawler.CrawlerID) []*crawler.Crawler2 {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range crawlerIDs {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetCrawlers", varargs...)
	ret0, _ := ret[0].([]*crawler.Crawler2)
	return ret0
}

// GetCrawlers indicates an expected call of GetCrawlers.
func (mr *MockCrawlerFactory2MockRecorder) GetCrawlers(ctx any, crawlerIDs ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, crawlerIDs...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCrawlers", reflect.TypeOf((*MockCrawlerFactory2)(nil).GetCrawlers), varargs...)
}
