services:
  rdb:
    build:
      dockerfile: Dockerfile.mysql
      context: .
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      LC_ALL: ja_JP.UTF-8
      LANG: ja_JP.UTF-8
      TZ: Asia/Tokyo
    volumes:
      - .conf.d:/etc/mysql/conf.d
    ports:
      - 3306:3306