// Code generated by MockGen. DO NOT EDIT.
// Source: crawler/internal/usecase/factory/crawler.go
//
// Generated by this command:
//
//	mockgen -source crawler/internal/usecase/factory/crawler.go -package factory -destination crawler/internal/usecase/factory/crawler_mock.go
//
// Package factory is a generated GoMock package.
package factory

import (
	context "context"
	reflect "reflect"

	crawler "github.com/suzuito/sandbox2-go/crawler/pkg/entity/crawler"
	gomock "go.uber.org/mock/gomock"
)

// MockCrawlerFactory is a mock of CrawlerFactory interface.
type MockCrawlerFactory struct {
	ctrl     *gomock.Controller
	recorder *MockCrawlerFactoryMockRecorder
}

// MockCrawlerFactoryMockRecorder is the mock recorder for MockCrawlerFactory.
type MockCrawlerFactoryMockRecorder struct {
	mock *MockCrawlerFactory
}

// NewMockCrawlerFactory creates a new mock instance.
func NewMockCrawlerFactory(ctrl *gomock.Controller) *MockCrawlerFactory {
	mock := &MockCrawlerFactory{ctrl: ctrl}
	mock.recorder = &MockCrawlerFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCrawlerFactory) EXPECT() *MockCrawlerFactoryMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockCrawlerFactory) Get(ctx context.Context, def *crawler.CrawlerDefinition) (*crawler.Crawler, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, def)
	ret0, _ := ret[0].(*crawler.Crawler)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockCrawlerFactoryMockRecorder) Get(ctx, def any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCrawlerFactory)(nil).Get), ctx, def)
}
