apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: dummy # from-param: bff-${location}-from-cloud-deploy
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: 0
        autoscaling.knative.dev/maxScale: 1
        run.googleapis.com/cloudsql-instances: products-common-common-202406:asia-northeast1:sandbox-instance
        run.googleapis.com/secrets: secret-alias-1:projects/1010894990875/secrets/mysql_sandbox_instance_user_password_app
    spec:
      serviceAccountName: photodx-bff-sa@photodx-prd-20240419.iam.gserviceaccount.com
      timeoutSeconds: 60
      containers:
        - image: app-image
          resources:
            limits:
              cpu: 1000m
              memory: 128Mi
          env:
            - name: ENV
              value: prd
            - name: PORT
              value: 8080
            - name: LOG_LEVEL
              value: DEBUG
            - name: DB_NAME
              value: photodx-prd
            - name: DB_USER
              value: app
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: "1"
                  name: secret-alias-1
            - name: DB_INSTANCE_UNIX_SOCKET
              value: /cloudsql/products-common-common-202406:asia-northeast1:sandbox-instance
            - name: CORS_ALLOW_ORIGINS
              value: https://pdx.tach.dev,https://photodx.tach.dev
            - name: CORS_ALLOW_METHODS
              value: GET
            - name: CORS_ALLOW_HEADERS
              value: Authorization
            - name: JWT_ADMIN_ACCESS_TOKEN_SIGNING_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  key: "1"
                  name: admin_access_token_signing_private_key
            - name: JWT_ADMIN_ACCESS_TOKEN_SIGNING_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  key: "1"
                  name: admin_access_token_signing_public_key
            - name: JWT_ADMIN_REFRESH_TOKEN_SIGNING_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  key: "1"
                  name: admin_refresh_token_signing_private_key
            - name: JWT_USER_ACCESS_TOKEN_SIGNING_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  key: "1"
                  name: user_access_token_signing_private_key
            - name: JWT_USER_ACCESS_TOKEN_SIGNING_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  key: "1"
                  name: user_access_token_signing_public_key
            - name: JWT_USER_REFRESH_TOKEN_SIGNING_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  key: "1"
                  name: user_refresh_token_signing_private_key
