apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: dummy # from-param: bff-${location}-from-cloud-deploy
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: 0
        autoscaling.knative.dev/maxScale: 1
    spec:
      serviceAccountName: photodx-bff-sa@photodx-prd-20240419.iam.gserviceaccount.com
      timeoutSeconds: 60
      containers:
        - image: app-image
          resources:
            limits:
              cpu: 1000m
              memory: 128Mi
          env:
            - name: ENV
              value: prd
            - name: hoge
              value: fuga
