name: check_in_main
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main

env:
  GO_VERSION: 1.22.x

jobs:
    gotest:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-go@v5
              with:
                go-version: ${{ env.GO_VERSION }}
            - run: sh test.sh ./...
            - uses: codecov/codecov-action@v4
              with:
                token: ${{ secrets.CODECOV_TOKEN }}