on:
  pull_request:
  push:
    branches:
      - main

jobs:
  blog-docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: .service/blog/Dockerfile.server