on:
  pull_request:
  push:
    branches:
      - main

jobs:
  common-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.21.x' ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDS }}'
      - run: make common-test
      - uses: codecov/codecov-action@v4
        with:
          flags: common
  blog-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.21.x' ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDS }}'
      - run: curl -L https://github.com/golang-migrate/migrate/releases/download/v4.16.0/migrate.linux-386.tar.gz | tar xvz && sudo mv ./migrate /bin/
      - run: make blog-init && make blog-init-rdb && make blog-test
      - uses: codecov/codecov-action@v4
        with:
          flags: blog
  crawler-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.21.x' ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDS }}'
      - run: make crawler-init && make crawler-test
      - uses: codecov/codecov-action@v4
        with:
          flags: crawler